
import { SelectOption } from './types';

export const TIME_OF_DAY_OPTIONS: SelectOption[] = [
  { value: "", label: "Pilih Waktu..." },
  { value: "Pagi hari cerah", label: "Pagi hari cerah (Bright Morning)" },
  { value: "Siang hari terik", label: "Siang hari terik (Blazing Noon)" },
  { value: "Sore hari keemasan", label: "Sore hari keemasan (Golden Afternoon)" },
  { value: "Senja", label: "Senja (Dusk)" },
  { value: "Malam berbintang", label: "Malam berbintang (Starry Night)" },
  { value: "Malam bulan purnama", label: "Malam bulan purnama (Full Moon Night)" },
  { value: "Dini hari berkabut", label: "Dini hari berkabut (Misty Dawn)" },
];

export const CAMERA_MOVEMENTS: SelectOption[] = [
  { value: "", label: "Pilih Gerakan Kamera..." },
  { value: "Static Shot", label: "Static Shot (Bidikan Statis)" },
  { value: "Zoom In (Slow)", label: "Zoom In - Lambat (Perbesar - Lambat)" },
  { value: "Zoom In (Fast)", label: "Zoom In - Cepat (Perbesar - Cepat)" },
  { value: "Zoom Out (Slow)", label: "Zoom Out - Lambat (Perkecil - Lambat)" },
  { value: "Zoom Out (Fast)", label: "Zoom Out - Cepat (Perkecil - Cepat)" },
  { value: "Pan Left (Slow)", label: "Pan Left - Lambat (Geser Kiri - Lambat)" },
  { value: "Pan Right (Slow)", label: "Pan Right - Lambat (Geser Kanan - Lambat)" },
  { value: "Tilt Up", label: "Tilt Up (Dongak ke Atas)" },
  { value: "Tilt Down", label: "Tilt Down (Tunduk ke Bawah)" },
  { value: "Dolly In", label: "Dolly In (Maju Mendekat)" },
  { value: "Dolly Out", label: "Dolly Out (Mundur Menjauh)" },
  { value: "Truck Left", label: "Truck Left (Geser ke Kiri - Kamera Bergerak)" },
  { value: "Truck Right", label: "Truck Right (Geser ke Kanan - Kamera Bergerak)" },
  { value: "Crane Up", label: "Crane Up (Naik ke Atas)" },
  { value: "Crane Down", label: "Crane Down (Turun ke Bawah)" },
  { value: "Tracking Shot / Follow Shot", label: "Tracking Shot (Mengikuti Objek)" },
  { value: "Orbit (Clockwise)", label: "Orbit - Searah Jarum Jam (Mengorbit - Searah Jarum Jam)" },
  { value: "Orbit (Counter-clockwise)", label: "Orbit - Berlawanan Jarum Jam (Mengorbit - Berlawanan Jarum Jam)" },
  { value: "Arc Shot (Left)", label: "Arc Shot - Kiri (Bidikan Melengkung - Kiri)" },
  { value: "Arc Shot (Right)", label: "Arc Shot - Kanan (Bidikan Melengkung - Kanan)" },
  { value: "Whip Pan", label: "Whip Pan (Geseran Cepat)" },
  { value: "Dutch Angle / Canted Angle", label: "Dutch Angle (Sudut Miring)" },
  { value: "Aerial Shot / Drone Shot", label: "Aerial Shot (Bidikan Udara/Drone)" },
  { value: "Low Angle Shot", label: "Low Angle Shot (Bidikan Sudut Rendah)" },
  { value: "High Angle Shot", label: "High Angle Shot (Bidikan Sudut Tinggi)" },
  { value: "First-person POV", label: "First-person POV (Sudut Pandang Orang Pertama)" },
  { value: "Third-person POV", label: "Third-person POV (Sudut Pandang Orang Ketiga)" },
  { value: "Handheld / Shaky Cam", label: "Handheld / Shaky Cam (Kamera Genggam/Goyang)" },
  { value: "Sequence Shot / Long Take", label: "Sequence Shot (Bidikan Rangkaian Panjang)" },
  { value: "Rolling Shot (Barrel Roll)", label: "Rolling Shot (Bidikan Bergulir)" },
  { value: "Push In", label: "Push In (Dorong Masuk)" },
  { value: "Pull Out", label: "Pull Out (Tarik Keluar)" },
  { value: "Fly-through", label: "Fly-through (Terbang Menembus)" },
  { value: "Boom Shot (Up/Down)", label: "Boom Shot - Naik/Turun (Bidikan Boom - Naik/Turun)" },
  { value: "Jib Shot", label: "Jib Shot (Bidikan Jib)" },
  { value: "Time-lapse", label: "Time-lapse (Selang Waktu)" },
  { value: "Slow Motion", label: "Slow Motion (Gerak Lambat)" },
  { value: "Hyperlapse", label: "Hyperlapse (Hiperlaps)" },
  { value: "Vertigo Effect / Dolly Zoom", label: "Vertigo Effect / Dolly Zoom (Efek Vertigo)" },
  { value: "Crash Zoom", label: "Crash Zoom (Zoom Tabrak)" },
  { value: "Snorricam Shot", label: "Snorricam Shot (Bidikan Snorricam)" },
  { value: "Gimbal Shot (Smooth)", label: "Gimbal Shot - Halus (Bidikan Gimbal - Halus)" },
  { value: "Reveal Shot", label: "Reveal Shot (Bidikan Pengungkapan)" },
];

export const LIGHTING_OPTIONS: SelectOption[] = [
  { value: "", label: "Pilih Pencahayaan..." },
  { value: "Golden Hour", label: "Golden Hour (Jam Emas)" },
  { value: "Studio Lighting", label: "Studio Lighting (Pencahayaan Studio)" },
  { value: "Neon Glow", label: "Neon Glow (Sinar Neon)" },
  { value: "Moonlit", label: "Moonlit (Cahaya Bulan)" },
  { value: "Volumetric Lighting", label: "Volumetric Lighting (Pencahayaan Volumetrik)" },
  { value: "Rim Lighting", label: "Rim Lighting (Pencahayaan Tepi)" },
  { value: "Silhouette", label: "Silhouette (Siluet)" },
  { value: "Dramatic Shadows", label: "Dramatic Shadows (Bayangan Dramatis)" },
  { value: "Bioluminescent", label: "Bioluminescent (Biopendar)" },
  { value: "Natural Light", label: "Natural Light (Cahaya Alami)" },
  { value: "Backlight", label: "Backlight (Cahaya Belakang)" },
  { value: "Chiaroscuro", label: "Chiaroscuro (Gelap Terang Kontras)" },
  { value: "Film Noir Lighting", label: "Film Noir Lighting (Pencahayaan Film Noir)" },
];

export const VIDEO_STYLES: SelectOption[] = [
  { value: "", label: "Pilih Gaya Video..." },
  { value: "Photorealistic", label: "Fotorealistik (Photorealistic)" },
  { value: "Cinematic", label: "Sinematik (Cinematic)" },
  { value: "Anime", label: "Anime" },
  { value: "Fantasy Art", label: "Seni Fantasi (Fantasy Art)" },
  { value: "Impressionistic", label: "Impresionistik (Impressionistic)" },
  { value: "Surreal", label: "Surealis (Surreal)" },
  { value: "Abstract", label: "Abstrak (Abstract)" },
  { value: "Pixel Art", label: "Seni Piksel (Pixel Art)" },
  { value: "3D Render", label: "Render 3D (3D Render)" },
  { value: "Claymation", label: "Animasi Tanah Liat (Claymation)" },
  { value: "Watercolor", label: "Cat Air (Watercolor)" },
  { value: "Documentary", label: "Dokumenter (Documentary)" },
  { value: "Vintage Film (8mm/16mm)", label: "Film Antik (8mm/16mm)" },
  { value: "VHS Glitch", label: "VHS Glitch (Gaya VHS Rusak)" },
  { value: "Cyberpunk", label: "Cyberpunk" },
  { value: "Steampunk", label: "Steampunk" },
  { value: "Gothic", label: "Gotik (Gothic)" },
  { value: "Minimalist", label: "Minimalis (Minimalist)" },
  { value: "Nature Documentary", label: "Dokumenter Alam" },
];

export const VIDEO_MOODS: SelectOption[] = [
  { value: "", label: "Pilih Suasana Video..." },
  { value: "Epic", label: "Epik (Epic)" },
  { value: "Mysterious", label: "Misterius (Mysterious)" },
  { value: "Serene / Calm", label: "Tenang / Damai (Serene / Calm)" },
  { value: "Tense / Suspenseful", label: "Tegang / Penuh Ketegangan (Tense / Suspenseful)" },
  { value: "Joyful / Uplifting", label: "Gembira / Membangkitkan Semangat (Joyful / Uplifting)" },
  { value: "Romantic", label: "Romantis (Romantic)" },
  { value: "Melancholic / Sad", label: "Melankolis / Sedih (Melancholic / Sad)" },
  { value: "Humorous / Comical", label: "Humoris / Lucu (Humorous / Comical)" },
  { value: "Dark / Ominous", label: "Gelap / Mengancam (Dark / Ominous)" },
  { value: "Whimsical / Playful", label: "Unik / Jenaka (Whimsical / Playful)" },
  { value: "Dreamlike", label: "Seperti Mimpi (Dreamlike)" },
  { value: "Action-packed", label: "Penuh Aksi (Action-packed)" },
  { value: "Nostalgic", label: "Nostalgia (Nostalgic)" },
];


export const GEMINI_MODEL_TEXT = 'gemini-2.5-flash-preview-04-17';
export const GEMINI_MODEL_IMAGE = 'imagen-3.0-generate-002';
